import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ravi.somepalli' at '4/15/16 6:00 AM' with Gradle 2.11
 *
 * @author ravi.somepalli, @date 4/15/16 6:00 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
